### ISSUE TITLE
version 1.18.2

### ISSUE THREAD

**Issue by riecaf** [FoggyHillside/End-s-Delight#1]
any plan fort newer port? also add image would be appreciated

**Comment by StormDragon-64** [comment]
Yes, also why did you start with 1.16 and then make it so you had to port it instead of just starting with 1.18.2 to begin with?

**Comment by Sshmoob** [comment]
Yes, the mod isn't getting many downloads because your still on 1.16. I want also this for my modpack.

**Comment by FoggyHillside** [comment]
I have a plan for 1.18.2, but it still needs some time to realize it.
