### ISSUE TITLE
All Drinks but Chorus Fruit Wine Includes an Eating Sound when they are consumed.

### ISSUE THREAD

**Issue by Fourbo** [FoggyHillside/End-s-Delight#11]
I don't know if this is intentional, but when consuming all of the drinks but the Chorus Fruit Wine, one of the eating sounds is played at the end. The video below shows me consuming all the drinks, and for comparison, I also included milk to show how the eating sound is not present.

https://github.com/FoggyHillside/End-s-Delight/assets/101537906/1e7d8bfb-2685-4964-b763-26579663a1ff

**Comment by FoggyHillside** [comment]
I haven't figured out how to stop that sound but I noticed that when consuming Apple Cider, an eating sound will also be played. 
So I submitted an issue to Farmer's Delight and this is the reply:
https://github.com/FoggyHillside/End-s-Delight/assets/108585746/9a5ae71b-8b56-4cea-9d70-dfbd08331741
