### ISSUE TITLE
Chorus Succulent does not spawn with BYG

### ISSUE THREAD

**Issue by Sanriaa** [FoggyHillside/End-s-Delight#16]
I was able to confirm by test removing BYG. If Biome's you'll go is installed, chorus succulent is replaced by a different block from that mod; conflicting item IDs I think

**Comment by Sanriaa** [comment]
I was able to confirm by test removing BYG. If Biome's you'll go is installed, chorus fruit is replaced by a different block from that mod; conflicting item IDs I think

**Comment by Sanriaa** [comment]
Sorry not chorus fruit, chorus succulents

**Comment by liangmoe** [comment]
In my test im using BYG and BetterEnd at the same time, i still can find chorus succulent but it only spawned on the original minecraft highlands biome

**Comment by FoggyHillside** [comment]
Chorus succulent still can be found in the minecraft vanilla biome end highlands in my test.
