### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by BR2066** [FoggyHillside/End-s-Delight#17]
Having an issue with the game crashing on startup, the error says:
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ends_delight'!"
I have attached the crash report, I'm wondering if it's conflicting with one of my other mods but I'm not sure.

[crash-2023-10-17_22.30.10-client.txt](https://github.com/FoggyHillside/End-s-Delight/files/12974596/crash-2023-10-17_22.30.10-client.txt)

**Comment by FoggyHillside** [comment]
Try to use newer version of Farmer's Delight.
