### ISSUE TITLE
Dragon Tooth & Knife Resprite

### ISSUE THREAD

**Issue by SABITRON** [FoggyHillside/End-s-Delight#18]
I made a retexture of the Dragon Tooth and Dragon Tooth Knife from this mod, you're free to use them if you think they look like an improvement (Old on top of image, new on bottom)
![teef](https://github.com/FoggyHillside/End-s-Delight/assets/44299493/4518de06-ac9a-43de-800d-e97ec2811125)
![dragon_tooth_knife](https://github.com/FoggyHillside/End-s-Delight/assets/44299493/b5ed1d2d-7565-41aa-9ee7-9d1f118d9a5b)
![dragon_tooth](https://github.com/FoggyHillside/End-s-Delight/assets/44299493/37fee20f-e884-4408-b40e-c1fc597db6ce)

**Comment by FoggyHillside** [comment]
Thanks for the retexture!
