### ISSUE TITLE
[Suggestion] Knife upgrades, and some cuisine recipes.

### ISSUE THREAD

**Issue by chemlzh** [FoggyHillside/End-s-Delight#19]
1. Could you please add some knife upgrades for dragon egg shell knife and dragon tooth knife? For example, you can fuse these two knife with an obsidian on smithing table to get enhanced knives, which comsunes netherite smithing upgrade template. Then you can fuse enhanced knives with an nether star to get upper-tier enhanced knives. Tier 1 and tier 2 enhanced knives will have a higher damage and provide some other buffs when attacking ender/shulker mobs.
请问作者能否给龙蛋壳刀和龙齿刀加个锻造升级的选项？例如说消耗一个锻造模板，可以在锻造台上用黑曜石镶嵌这两把小刀，得到强化后的小刀，之后再用下界之星按相似方法镶嵌，得到进一步强化的小刀。强化一次/两次后的小刀威力比原始小刀高（可以搞成+1/+2），并且在攻击末影/潜影生物时（包括末影人、末影龙、潜影贝，如果有额外模组可以配置），附带一定的对自身buff或对攻击对象debuff。

2. I have figured out some cuisine recipes. May be you can add these cuisines in the future version.
我想了一些菜肴和配方，希望以后可以被加进未来的末地乐事里。（我自己不会画画，没法发贴图，数值也没想好怎么平衡，但大致的buff应该能给下的，至于等级和持续时间就交给作者大大权衡了）

Shulker soup with kelp: can be crafted by boiling shulker meat, kelp, dried chorus flower and onion (since Farmer's delight doesn't have wax gourd) in the pot. Must be contained with a bowl. Can provide nourish, health regeneration and resistance effect. Return bowl used in craft recipes.
海带潜影贝汤（原型花蛤汤）：由潜影贝肉、海带、干紫颂花和洋葱在锅里烹煮而成，用木碗或其他碗盛装。提供滋养，生命恢复，抗性提升效果。食用后返还合成时用的碗。

Shulker omelette: need to craft raw shulker omelette using liquid dragon egg, shulker meat, wheat (or wheat flour from other mods) and dried chorus flower (or some other vegetables, I haven't figure it out yet) with a bowl on the crafting table. Then cook raw shulker omelette on skillet (or stove/furnace/smoker) to obtain shulker omelette. Can provide nourish, health regeneration, strength, absorption and resistance. Return bowl used in craft recipes.
潜影贝煎（原型海蛎煎）：先由龙蛋液、潜影贝肉、小麦（可用其他模组的面粉代替）和干紫颂花（或其他蔬菜，我还没想好）和木碗在工作台上合成生潜影贝煎，然后在煎锅（或者扔炉灶/熔炉/烟熏炉也可以）上烹饪得到。提供滋养，生命恢复，力量，伤害吸收，抗性提升效果。食用后返还合成时用的碗。

End yangchun (splendid spring?) noodles: can be crafted by boiling noodles, shulker meat, raw ender mite meat, liquid dragon egg, cabbage (why does not Farmer's Delight have implemented bok choy?) and brown mushroom in the pot. Must be contained with a half dragon egg shell. Can provide nourish, health regeneration, max health increase, strength, absorption and resistance. Return bowl used in craft recipes.
末地阳春面（原型阳春面，融合了海鲜沙茶面的点子）：由潜影贝肉、生末影螨肉、龙蛋液、卷心菜（为什么农夫乐事没小白菜？！）、棕色蘑菇在锅里烹煮而成，用半个龙蛋壳盛装（因此还要用木碗分装为可食用状态，下同）。提供滋养，生命恢复，生命提升，力量，伤害吸收，抗性提升效果。食用后返还合成时用的碗。

Dragon steak gaifan (Dragon steak with rice): can be crafted by stir-frying raw dragon meat, rice, ender sauce, tomato, potato and cabbage in the pot. Must be contained with a half dragon egg shell. Can provide nourish, comfort, health regeneration, strength and resistance. Return bowl used in craft recipes.
龙排盖浇饭（原型鸡排饭、卤肉饭等）：由生龙肉、稻米、末影酱、番茄、土豆和卷心菜在锅里爆炒而得，用半个龙蛋壳盛装（因此还要用木碗分装为可食用状态，下同）。提供滋养，舒适，生命恢复，力量，抗性提升效果。食用后返还合成时用的碗。

Dragon meat zongzi (rice dumpling): can be crafted by stewing roasted dragon meat, rice, one of the mushrooms (red, brown, warped or crimson) and ender sauce in the pot. Must be contained with bamboo leaves, which can be obtained by cutting bamboo with a knife on the cutting board (sticks can be obtained at the same time). Can provide nourish, absorption and health regeneration.
龙肉粽（原型烧肉粽）：由烤龙肉、稻米、原版任意一种蘑菇和末影酱在锅里蒸煮而得，用竹叶盛装，竹叶可由竹子在砧板上用小刀切削而得，同时得到木棍。提供滋养，伤害吸收，生命恢复。

Dragon breath zongzi (rice dumpling): can be crafted by stewing dragon breath, rice and honey (or cane sugar) in the pot. Must be contained with bamboo leaves. Can provide nourish, strength and resistance.
龙息粽（原型碱水粽）：由龙息、稻米、蜂蜜或蔗糖在锅里蒸煮而得，用竹叶盛装。提供滋养，力量，抗性提升。

That's all I have thought. Thank you!
目前想到的就这些。谢谢作者大大！

**Comment by chemlzh** [comment]
后面我把这个提议转到群里，让群友提提数值上的建议，群友的意见和改动如下，就不翻译成英文了：

1、希望能够像钻石工具升级下界合金那样给龙齿刀和龙蛋壳刀加入升级配方？例如利用刀具升级模板和下界之星在锻造台上将龙齿刀或者龙蛋壳刀升级，升级后数据可以改为伤害6.5，攻击速度2，配合暴击满配dps几乎与满配下界合金剑一致（26左右）。考虑到造价高昂，可以给其附加一些特殊属性如对末地生物额外伤害。

2、我自己有一些想法，希望能够帮忙增加一些菜肴丰富末地乐事的内容。（属性都是参照现有的菜大致估摸着给出的，仅仅只是作为建议和参考）

（1）海带潜影贝汤（灵感来自于花蛤汤）
	配方：（厨锅）潜影贝肉/潜影贝肉片，干海带，紫颂多肉植物，洋葱→1*海带潜影贝汤。使用碗进行盛装。堆叠数为16。
	效果：饥饿度*12，饱和度*19.2；2s漂浮II；6s生命恢复II；3min舒适；60s伤害吸收I。

（2）潜影贝煎（灵感来源于海蛎煎）
	配方：（工作台）鸡蛋，潜影贝肉/潜影贝肉片，面团，干紫颂花，胡萝卜，碗→1*生潜影贝煎；（熔炉）生潜影贝煎→1*潜影贝煎，堆叠数为16
	效果：饥饿度*12，饱和度*19.2；60s力量I；60s伤害吸收I；8s生命恢复II；3min滋养。

（3）末地阳春面（灵感来源于阳春面和海鲜沙茶面）
	配方：（厨锅）潜影贝肉/潜影贝肉片，末影螨肉干，龙蛋液，卷心菜/卷心菜叶，棕色蘑菇，意面→1*末地阳春面。使用半个龙蛋壳进行盛装。使用碗右击末地阳春面可获得4*碗装末地阳春面。晚装末地阳春面堆叠数为16，末地阳春面堆叠数为1。
	效果：饥饿度*14，饱和度*21；90s力量II；90s抗性提升II；90s生命恢复II；90s伤害吸收III；90s生命提升III；5min滋养。

（4）龙排盖浇饭（灵感来源鸡排饭）
	配方：（厨锅）生龙肉/生龙肉块，稻米，末影酱，番茄，马铃薯，卷心菜/卷心菜叶→龙排盖浇饭，堆叠数1；对龙排盖浇饭拿着碗右击可获得4*碗装龙排盖浇饭。堆叠数16.
	效果：饥饿度*14，饱和度*21；30s力量II；60s伤害吸收III；15s生命恢复II；5min滋养。

（5）龙肉粽（咸粽子）
	配方：（厨锅）烤龙肉/烤龙肉块，稻米，末影酱→1*龙肉粽，使用粽叶进行盛装（竹子在砧板上用刀切可以获得木棍和粽叶），堆叠数16
	效果：饥饿度*10，饱和度*14；30s力量II；15s生命恢复II；30s伤害吸收III；3min滋养

（6）龙息粽（甜粽子）
	配方：（厨锅）龙息，稻米，糖→1*龙息粽，使用粽叶进行盛装，堆叠数16
	效果：饥饿度*10，饱和度*14；45s力量I；45s抗性提升I；15s生命恢复II；3min舒适。

**Comment by FoggyHillside** [comment]
十分感谢！会考虑加入到之后的更新计划里的
