### ISSUE TITLE
ender Sauce stacks up to 16

### ISSUE THREAD

**Issue by tankplanelaserkoala** [FoggyHillside/End-s-Delight#23]
Mod Version: 1.20.1

Game Version: 1.20.1

Forge version: 47.2.20

According to the Farmer’s Delight crew(https://github.com/vectorwing/FarmersDelight/issues/873), if the dish contained in a bowl serves as an ingredient, it should be stacked 64 times, rather than the 16 times previously thought to be the farmer’s Delight mode cooking rule.

Change the ender sauce to stack in stacks of 64.

**Comment by FoggyHillside** [comment]
It is 64 now in the new versions of 1.20.1-2.X
