### ISSUE TITLE
[Compat] Mod no longer works with original Farmer's Delight [Fabric] port.

### ISSUE THREAD

**Issue by SafTheLamb** [FoggyHillside/End-s-Delight#25]
With the update to support Farmer's Delight Refabricated, the mod no longer works with the original Farmer's Delight [Fabric] mod... I'm very confused, have the devs for the original port stated they're discontinuing it, or are these two different competing ports now?

**Comment by FoggyHillside** [comment]
End's Delight Refabricated and End's Delight Fabric are specific versions supporting Farmer's Delight Refabricated and Farmer's Delight [Fabric] respectively.
By the way, I just noticed that the devs for the original Farmer's Delight [Fabric] mod stated that Farmer's Delight [Fabric] is deprecated and no longer being updated.
