### ISSUE TITLE
There are two items for Dragon Leg with Sauce

### ISSUE THREAD

**Issue by Billnotic** [FoggyHillside/End-s-Delight#28]
Dragon Leg With Sauce is the item which is craftable, but inedible. Plate of Dragon Leg With Sauce IS edible, but uncraftable. Not sure what happened here.

**Comment by FoggyHillside** [comment]
Dragon Leg with Sauce is placeable, so you can hold a bowl on your hand, right click on the Dragon Leg with Sauce BLOCK and then you'll get a Plate of Dragon Leg with Sauce.

**Comment by Billnotic** [comment]
Ah, my bad. I've been testing stuff with my modpack before actually playing proper so I didn't experience it organically. Sorry to bother you.
