### ISSUE TITLE
Farmer's Respite compat?

### ISSUE THREAD

**Issue by WaterOre** [FoggyHillside/End-s-Delight#3]
When Farmer's Respite is installed, recipes for the teas added by this mod should be craftable using their kettle. None of the recipes include more than two ingredients + a base serving container, and they thematically fit with other drinks produced using the kettle.
![image](https://user-images.githubusercontent.com/46122502/226219513-2454aaea-0ed2-430e-9977-c5c0e95d5a73.png)

**Comment by FoggyHillside** [comment]
Now some drinks can be made using the kettle in version 1.19.2-1.1
