### ISSUE TITLE
2.2版本装上时崩溃了

### ISSUE THREAD

**Issue by Golder114514** [FoggyHillside/End-s-Delight#35]
[crash-2024-06-28_14.42.50-server.txt](https://github.com/user-attachments/files/16025456/crash-2024-06-28_14.42.50-server.txt)

**Comment by FoggyHillside** [comment]
崩溃报告里说安装的是2.1版本（虽然说2.2也可能崩…… 要是一直崩的话可以安个旧版本（2.X更新之前的），或者试试Neruina（不太确定能不能生效），再或者我记得 Forge 应该有可以处理 Ticking Entity 问题的 removeErroringTileEntities 设置（forge.cfg 里）改成 true，生效后再改回 false 就行

如果有兴趣的话未来可以试试GitHub里的测试版（今天应该就会发布一版），现在我这边还不能复现这个崩溃，所以也不太能测试修复效果，如果能帮忙测试一下的话就太感谢了，当然不方便的话也没关系的

**Comment by FoggyHillside** [comment]
可以用2.3版本了
