### ISSUE TITLE
[Bug]Cause a crash on fabric server

### ISSUE THREAD

**Issue by LiuQiYu671** [FoggyHillside/End-s-Delight#39]
[crash-2024-07-05_14.12.35-server.txt](https://github.com/user-attachments/files/16105720/crash-2024-07-05_14.12.35-server.txt)
It seems that the DragonTeethKnife cause the bug.
(P.S.:My English is bad,sorry.)

**Comment by FoggyHillside** [comment]
This issue is fixed in the new version of refabricated-1.20.1-2.1

**Comment by LiuQiYu671** [comment]
thx
