### ISSUE TITLE
Crash upon eating Chorus Fruit Pie Block

### ISSUE THREAD

**Issue by JadeiteWren** [FoggyHillside/End-s-Delight#42]
[crash-2024-08-21_22.54.35-client.txt](https://github.com/user-attachments/files/16703415/crash-2024-08-21_22.54.35-client.txt)

<details> ---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-08-21 22:54:35
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.class_1799 cn.foggyhillside.ends_delight.block.ChorusFruitPieBlock.getPieSliceStack()'
	at cn.foggyhillside.ends_delight.block.ChorusFruitPieBlock.consumeBite(ChorusFruitPieBlock.java:35)
	at vectorwing.farmersdelight.common.block.PieBlock.method_9534(PieBlock.java:78)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
	at net.minecraft.class_636.method_41934(class_636.java:347)
	at net.minecraft.class_636.method_41933(class_636.java:324)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:323)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.method_1508(class_310.java:2052)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cn.foggyhillside.ends_delight.block.ChorusFruitPieBlock.consumeBite(ChorusFruitPieBlock.java:35)
	at vectorwing.farmersdelight.common.block.PieBlock.method_9534(PieBlock.java:78)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133)
	at net.minecraft.class_636.method_41934(class_636.java:347)
	at net.minecraft.class_636.method_41933(class_636.java:324)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2896(class_636.java:323)
	at net.minecraft.class_310.method_1583(class_310.java:1802)
	at net.minecraft.class_310.method_1508(class_310.java:2052)

-- Affected level --
Details:
	All players: 1 total; [class_746['JadeiteWren'/143, l='ClientLevel', x=180.45, y=85.00, z=2245.90]]
	Chunk stats: 16384, 3653
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,67,0), Section: (at 0,3,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 39772 game time, 25299 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, $polymer-resources, Moonlight Mods Dynamic Assets

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.9, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 718545856 bytes (685 MiB) / 4454350848 bytes (4248 MiB) up to 12482248704 bytes (11904 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900X 12-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=31.0.14051.5006
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 40874.27
	Virtual memory used (MB): 28725.72
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 1418.23
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx11904M
	Fabric Mods: 
		adorn: Adorn 5.0.1+1.20.1
		almostunified: AlmostUnified 1.20.1-0.9.4
		alternate-current: Alternate Current 1.8.0-beta.4
		amendments: Amendments 1.20-1.2.8
		amethyst_cutting_mr: Amethyst Cutting 1.0
		amplified_nether: Amplified Nether 1.2.5
		analog: Analog 1.2.0+1.20.1
			com_github_trilarion_java-vorbis-support: java-vorbis-support 1.2.1
			net_lingala_zip4j_zip4j: zip4j 2.11.5
			polymer-blocks: Polymer (Textured Blocks) 0.5.7+1.20.1
			polymer-core: Polymer (Core) 0.5.7+1.20.1
				polymer-networking: Polymer (Networking) 0.5.7+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.7+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.7+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.7+1.20.1
				polymer-common: Polymer (Common) 0.5.7+1.20.1
					packet_tweaker: Packet Tweaker 0.4.0+1.19.4
			sgui: sgui 1.2.2+1.20
		another_furniture: Another Furniture 1.20.1-3.0.1
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		athena: Athena 3.1.2
		audioplayer: AudioPlayer 1.20.1-1.10.2
			admiral: Admiral 0.4.4+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
		azurelib: AzureLib 2.0.31
		backpacked: Backpacked 3.0.0-beta.4
			mm: Manningham Mills 2.3
		backported_wolves: Backported Wolves 1.1.0-1.19.3-1.20.4
		barbequesdelight: Barbeque's Delight 1.0.8
		beautify: Beautify 1.2.0+1.20.1
		bellsandwhistles: Create: Bells & Whistles 0.4.5
		bettercombat: Better Combat 1.8.6+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.4
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.6
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.6
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.5
		betterladdersmod: Better Ladders 0.0.2.1.20.1
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		bettertridents: Better Tridents 8.0.1
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		blahaj: Blåhaj 0.3.2
		bookshelf: Bookshelf 20.2.13
		botarium: Botarium 2.3.4
			team_reborn_energy: Energy 3.0.0
		brewinandchewin: Brewin And Chewin 3.0.6+1.20.1
		bushierflowers: Bushier Flowers 0.0.3-1.20.1
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		casualness_delight: Casualness Delight Fabric 1.20.1-0.4-FDR
		chefsdelight: Chefs Delight 1.0.3-fabric-1.20.1
		chimes: Chimes 2.0.1
		chipped: Chipped 3.0.6
		chunky: Chunky 1.3.146
		chunkyborder: ChunkyBorder 1.1.53
		cinderscapes: Cinderscapes 4.0.10
			biolith: Biolith 1.0.0-beta.1
			cinderscapes-client: Cinderscapes: Client 4.0.10
			cinderscapes-common: Cinderscapes: Common 4.0.10
			cinderscapes-worldgen: Cinderscapes: World Generation 4.0.10
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 7.0.3
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.3
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.3
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.3
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.4
		clutter: Clutter 1.20-0.5.9
		collective: Collective 7.81
		comforts: Comforts 6.4.0+1.20.1
			spectrelib: SpectreLib 0.13.15+1.20.1
		companion: Companion 5.2.0
		convenient-mobgriefing: Convenient mobGriefing 2.1.0
		copper_rails: Copper Powered Rails 1.2
		copperhopper: Copper Hopper 0.5.1+1.20.1
		copycats: Create: Copycats+ 2.1.2+mc.1.20.1-fabric
		corndelight: Corn Delight 1.1.2
		cratedelight: Crate Delight 24.8.9-1.20-fabric
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create-trimmed: create-trimmed 1.0.0
		createdeco: Create Deco 2.0.2-1.20.1-fabric
		createfood: Create: Food 1.1.0
		culturaldelights: Cultural Delights Fabric 1.0.5+1.20.1
		debugify: Debugify 1.20.1+2.0
		dogslie: Let Sleeping Dogs Lie 1.3.0
		doubledoors: Double Doors 5.9
		dramaticdoors: Dramatic Doors (QuiFabrge) 1.20.1-3.2.3
		dummmmmmy: MmmMmmMmmMmm 1.20-1.8.20
		dustydecorations: Dusty Decorations Refabricated 1.1-1.20.1
		enchdesc: EnchantmentDescriptions 17.0.16
		ends_delight: End's Delight 2.0
			porting_lib_config: Porting Lib Config 2.3.4+1.20.1
				porting_lib_core: Porting Lib Core 2.3.4+1.20.1
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		expandeddelight: Expanded Delight 0.3.1
			omega-config: OmegaConfig 1.4.0+1.20.1
		exposure: Exposure 1.7.5
		extrakeybinds: ThatRobins Extra Origins Keybinds 0.5.0+1.17-1.19.4
		extraorigins: Extra Origins 1.20-8
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.0+kotlin.2.0.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.2
			mixinextras: MixinExtras 0.4.1
		farmersdelight: Farmer's Delight 1.20.1-2.1.2+refabricated
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
				porting_lib_common: Porting Lib Common 2.3.4+1.20.1
				porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
				porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.4+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.4+1.20.1
			porting_lib_registries: Porting Lib Registries 2.3.4+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
		farmersdelightexpansion: Farmer's Delight Expansion 1.2.1+1.20.1
		farmersknives: Farmer's Knives 3.2
		fennecfox: Fennec Fox 1.0.0
		ferritecore: FerriteCore 6.0.1
		figura: Figura 0.1.4+1.20.1
			com_github_figuramc_luaj_luaj-core: luaj-core 3.0.8-figura
			com_github_figuramc_luaj_luaj-jse: luaj-jse 3.0.8-figura
			com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		flowerymooblooms: Friends&Foes - Flowery Mooblooms 2.0.2
		forgeconfigapiport: Forge Config API Port 8.0.0
		framework: Framework 0.7.6
			org_javassist_javassist: javassist 3.29.2-GA
		friendsandfoes: Friends&Foes 2.0.16
		frightsdelight: Frights Delight fabric-1.20.1-1.0.4
		furnish: Furnish 26
		geckolib: GeckoLib 4 4.4.7
			com_eliotlash_mclib_mclib: mclib 20
		handcrafted: Handcrafted 3.0.6
		hearth_and_home: Hearth & Home 1.20.1-2.0.3
		herbaldelight: Herbal Delight 1.3-patch3-1.20.1
		horsebuff: HorseBuff 2.1.2
		iceberg: Iceberg 1.1.18
		ichunutil: iChunUtil 1.0.0
		immersive_melodies: Immersive Melodies 0.3.0+1.20.1
		indium: Indium 1.0.34+mc1.20.1
		interiors: Create: Interiors 0.5.3+fabric-mc1.20.1
		itemfig: ItemFig 1.20.1-0.2.7-fabric
		itemsortermod: ItemSorterMod 1.10.3+1.20.1
		jade: Jade 11.9.2+fabric
		jamlib: JamLib 0.6.1+1.20.x
		java: OpenJDK 64-Bit Server VM 17
		kiwi: Kiwi Library 11.8.19+fabric
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		letmedespawn: Let Me Despawn 1.2.1
		lexiconfig: Lexiconfig 1.3.11
		lithium: Lithium 0.11.2
		logical_zoom: Logical Zoom 0.0.20
		malilib: MaLiLib 0.16.3
		mcwbridges: Macaw's Bridges 3.0.0
		mcwfences: Macaw's Fences and Walls 1.1.2
		mcwpaths: Macaw's Paths and Pavings 1.0.5
		mcwwindows: Macaw's Windows 2.3.0
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		moborigins: Mob Origins 1.11.1
		modelfix: Model Gap Fix 1.15
		modernfix: ModernFix 5.19.1+mc1.20.1
		moonlight: Moonlight 1.20-2.12.10
		moreculling: More Culling 1.20.4-0.24.0
			conditional-mixin: conditional mixin 0.3.2
			mixinsquared: MixinSquared 0.1.1
		moredelight: More Delight 1.2.2-1.20.1-fabric
		mr_developer_resources: Data API 0.2
		mr_origins_dietarydelights: Origins: Dietary Delights 1.5.2
		mythic_charms: Mythic Charms 1.1.2
		naturalist: Naturalist 4.0.3
		neruina: Neruina 2.1.1
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.17.0
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.17.0
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.17.0
			org_apache_maven_maven-artifact: maven-artifact 3.8.1
			org_kohsuke_github-api: github-api 1.318
		nethersdelight: Nether's Delight Refabricated 1.20.1-4.1.1
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		notenoughanimations: NotEnoughAnimations 1.7.4
		nullscape: Nullscape 1.2.7
		numismatics: Create: Numismatics 1.0.6+fabric-mc1.20.1
		oceansdelight: Ocean's Delight fdrf-fabric-1.0.2-1.20
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				additionalentityattributes: Additional Entity Attributes 1.3.0+1.20.0
				calio: Calio 1.11.0
				playerabilitylib: Pal 1.8.0
		originsumbrellas: Origins: Umbrellas 1.5.6
		ottah: OttahMod A2-pre_2
		overworldpiglins: Overworld Piglins 1.5
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		pandaplushies: Panda Plushies! 1.1
		passiveendermen: Passive Endermen 4.8
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.8.3+1.14.4-1.21
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		perfectplushies: Perfect Plushies 1.11.0
			perfectplushieapi: Perfect Plushie API 0.1.1
		phantomslma: Friendly Phantoms 0.1.1
		pineapple_delight: Pineapple Delight 1.0.10
		player-animator: Player Animator 1.0.2-rc1+1.20
		polymorph: Polymorph 0.49.5+1.20.1
		presencefootsteps: Presence Footsteps 1.9.0
			kirin: Kirin UI 1.15.0
		pumpkin_pie: Pumpkin Pie Delight 1.0.1
		puresmores: Pure S'mores 1.1.0
		puzzleslib: Puzzles Lib 8.1.21
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		railways: Create: Steam 'n' Rails 1.6.4+fabric-mc1.20.1
		randombonemealflowers: Random Bone Meal Flowers 4.6
		rch_supplementaries_compat: RightClickHarvest Supplementaries Compat 1.0.0
		redeco: Re:Deco 0.12.0.0
		resourcefulconfig: Resourcefulconfig 2.1.2
		resourcefullib: Resourceful Lib 2.1.28
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		ribbits: Ribbits 1.20.1-Fabric-3.0.0
		rightclickharvest: Right Click Harvest 3.2.3+1.19.x-1.20.1-fabric
		roughlyenoughitems: Roughly Enough Items 12.1.750
			error_notifier: Error Notifier 1.0.9
		sawmill: Universal Sawmill 1.20-1.4.3
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		silentsdelight: Silents Delight fabric-1.0.2-1.20.1
		silveroak: Silveroak Outpost 1.1.0-Alpha
		sliceanddice: Create Slice & Dice 3.2.3
		smartbrainlib: SmartBrainLib 1.14.2
		snifferplus: Hellion's Sniffer+ 0.3.0
		sodium: Sodium 0.5.11+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		soulcandles: Soul Candles 1.1.0
		spark: spark 1.10.53
		sparsestructures: SparseStructures 2.2.0
		starlight: Starlight 1.1.2+fabric.dbc156f
		stendhal: Stendhal 1.4.1-1.20
			libgui: LibGui 8.0.1+1.20
				jankson: Jankson 5.0.1+j1.2.2
				libninepatch: LibNinePatch 1.2.0
		storagedelight: Storage Delight 2024.7.23-1.20.1-fabric
		styled-nicknames: Styled Nicknames 1.2.1+1.20
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-pre.2+1.19.3
			player-data-api: Player Data API 0.2.2+1.19.3
		supplementaries: Supplementaries 1.20-2.8.17
		suppsquared: Supplementaries Squared 1.20-1.1.14
		terrablender: TerraBlender 3.0.1.7
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		terralith: Terralith 2.5.4
		toomanyorigins: TooManyOrigins 1.1.2+1.20.1-fabric
			apugli: Apugli 2.10.2+1.20.1-fabric
				midnightlib: MidnightLib 1.4.1
			wwfix: Water Walking Fix 1.0.0+hotfix.1
		touhouorigins: Touhou Origins 1.0.2
		trinkets: Trinkets 3.7.2
		twigs: Twigs 3.1.0
		ubesdelight: Ube's Delight 1.20.1-0.1.5.4
		vanilla_degus: Vanilla Degus 1.5.0
		vcinteraction: Voice Chat Interaction 1.20.1-1.0.6
		voicechat: Simple Voice Chat 1.20.1-2.5.20
		weaponworks: weaponworks 1.4.1-1.20.1-fabric
		wildlife: Wildlife 1.19.2-2.2
		windchimes: Windchimes 1.2.4+1.20
		xercapaint: Joy of Painting fabric-1.20.1-1.0.1
		ydms_redpanda: YDM's Red Panda 1.0.4
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.5
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon RX 5700 XT GL version 3.2.0 Core Profile Context 23.4.3.230420, ATI Technologies Inc.
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 24x AMD Ryzen 9 3900X 12-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['JadeiteWren'/143, l='ServerLevel[New World]', x=180.45, y=85.00, z=2245.90]]
	Data Packs: vanilla, fabric, $polymer-resources, Moonlight Mods Dynamic Assets, Supplementaries Generated Pack, Suppsquared Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable</details>

**Comment by FoggyHillside** [comment]
Use the latest version marked with 'refabricated' of End's Delight. Versions marked with 'refabricated' rather than 'fabric' are compatible with Farmer's Delight Refabricated.
