### ISSUE TITLE
Crash while attempting to eat `chorus_fruit_pie`

### ISSUE THREAD

**Issue by MikiP98** [FoggyHillside/End-s-Delight#47]
**Mod loader:** *Fabric 0.16.7*
**MC version:** *1.20.1*
**End's Delight version:** *(newest) 2.1*
**Farmer's Delight Refabricated:** *2.1.6*

**Crash Report:**
[crash-2024-11-01_23.31.05-client.txt](https://github.com/user-attachments/files/17606701/crash-2024-11-01_23.31.05-client.txt)
```
java.lang.NoSuchMethodError: 'net.minecraft.class_1799 cn.foggyhillside.ends_delight.block.ChorusFruitPieBlock.getPieSliceStack()'
	at knot//cn.foggyhillside.ends_delight.block.ChorusFruitPieBlock.consumeBite(ChorusFruitPieBlock.java:35)
	at knot//vectorwing.farmersdelight.common.block.PieBlock.method_9534(PieBlock.java:78)
        at ...
        ...
```

**Comment by FoggyHillside** [comment]
There are two types of Fabric version of this mod now, Fabric (For [[Deprecated] Farmer's Delight [Fabric]](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)) and Refabricated (For [Farmer's Delight Refabricated](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated)). You seem to be using the wrong version.

**Comment by MikiP98** [comment]
Oh I see...
Well it works now, though it is somewhat confusing, and the mod shows as outdated now.
As the deprecated versions is well... deprecated, shouldn't the refabricated version be the main one?

**Comment by FoggyHillside** [comment]
That is because the latest Fabric version of End's Delight was released later than the latest Refabricated version. It seems that the default display order (release time) of them cannot be changed on both CurseForge and Modrinth, or I do not know how to change it. So, I have just added "FDF" or "FDRF" above names of some versions to make it easier to distinguish them.

**Comment by MikiP98** [comment]
I guess if Modrinth does not have any way of fixing this I will close this issue.

You can however split the mod into 2:
- End's Delight Refabricated
- [Deprecated] End's Delight

Or somethin similar.
I will understand if you don't though.

You can also just drop the support for the deprecated version and release version 2.1.1 with the only purpose of being the newest.
