### ISSUE TITLE
How do you get the Suspicious Dragon Core?

### ISSUE THREAD

**Issue by katubug** [FoggyHillside/End-s-Delight#5]
Hi, do you have a Discord? I'm messing around with the newest version and I have some questions.

**Comment by FoggyHillside** [comment]
Sorry, but I don't have. Maybe I will create a wiki as a tutorial.

**Comment by katubug** [comment]
That works. In the meantime, can you tell me how to get the suspicious
dragon core? It seems like it didn't drop from the end dragon when I tested
it

**Comment by FoggyHillside** [comment]
Kill the ender dragon with knife then it will drop.

**Comment by katubug** [comment]
Ah okay, thanks!
