### ISSUE TITLE
Compatibility Issue - 1.20.1

### ISSUE THREAD

**Issue by zachsai** [FoggyHillside/End-s-Delight#9]
For compatibility sake, please change this recipe to use forge:dough tag instead of farmersdelight:wheat_dough item

![image](https://github.com/FoggyHillside/End-s-Delight/assets/63996164/62f6ef7c-c074-4e6b-9e3f-2c5b95130701)
![image](https://github.com/FoggyHillside/End-s-Delight/assets/63996164/7cd73c72-c500-42d8-bfce-8d8775b8655f)

This will allow other doughs to be used such as create's dough

**Comment by FoggyHillside** [comment]
Done
